#!/bin/sh

#
# simtool
#
/usr/bin/invoke_app "$@" -t vaspingestor \
                         -C "start_jupyter -t -T @tool bin/landing_page.ipynb" \
                         -u anaconda-7 \
                         -w headless \
                         -r none
